### ISSUE TITLE
Pickling is not enabled.

### ISSUE THREAD

**Issue by felipecode** [carla-simulator/map#27]
The objects from the python biding of the admap are not serializable through pickling. 
So it is not really possible to have then as class attributes for many applications.

This code snippet showcases the problem.

```
import ad.map
import copy

class CityMap(object):
    
    def __init__(self, open_drive_map): 
        ad.map.access.init(open_drive_map)
        self.lanes_id = ad.map.lane.getLanes()


city_map = CityMap('sample_maps/TPK.adm.txt')
map_copy = copy.deepcopy(city_map)
```

**Comment by berndgassmann** [comment]
You have to remember that the python interface is code generated from the C++ code. I don't know if there is a possibility to integrate pickling support here in conjunction with Py++, indexing_suite, etc. If you know how to do such, you are welcome to provide support.
If Py++ doesn't offer such support I fear that this might be not possible to provide with meaningful effort...
Any ideas?
