### ISSUE TITLE
Is this map module used in Carla Simulator ?

### ISSUE THREAD

**Issue by zwkcoding** [carla-simulator/map#49]
When I looked into this repo, I found some introduction about `adm` . 
However I wonder what the relation between this module and Carla simulato main repo is ?
Could someone help me to understand it.
Thxs

**Comment by zwkcoding** [comment]
BTW, It's better understanding to give some tips about where this map lib is used.
I found it's used in [RssSensor](https://github.com/carla-simulator/carla/blob/fe3cb6863a604f5c0cf8b692fe2b6300b45b5999/LibCarla/source/carla/rss/RssSensor.cpp#L74), could give more usage example.

**Comment by zwkcoding** [comment]
One more thing, interesting thing, I found [ad-rss-lib](https://github.com/intel/ad-rss-lib/tree/master/dependencies)  was built on this map module. Oh-ha. gotta it.
But I really want to know whether the module is used for other features in carla simulator, there also is [Road](https://github.com/carla-simulator/carla/blob/master/LibCarla/source/carla/road/Lane.cpp) implement, what is the difference ?

**Comment by berndgassmann** [comment]
Hi, 
without proper handling of map data, the RssSensor wouldn't have been possible. The core parts of interaction with the map for the sensor is described here: https://intel.github.io/ad-rss-lib/ad_rss_map_integration/Main/

The core parts on the ad_map_opendrive_reader comes actually from the code within CARLA. But the effort to use of ad-map interface within CARLA implementation itself besides the RssSensor, is not taken yet.

In future the library will also be used for other new features as it provides a rich feature set on how to analyze and interact with AD-map data.

Bernd.

**Comment by zwkcoding** [comment]
> Hi,
> without proper handling of map data, the RssSensor wouldn't have been possible. The core parts of interaction with the map for the sensor is described here: https://intel.github.io/ad-rss-lib/ad_rss_map_integration/Main/
> 
> The core parts on the ad_map_opendrive_reader comes actually from the code within CARLA. But the effort to use of ad-map interface within CARLA implementation itself besides the RssSensor, is not taken yet.
> 
> In future the library will also be used for other new features as it provides a rich feature set on how to analyze and interact with AD-map data.
> 
> Bernd.

At first, thanks for your fast reply. I understand the design philosophy behind the scene at now.
Thanks for developing such a HD Map library, looking forward to more active improvements and applications :clap:
