### ISSUE TITLE
Qgis import error: metadata file is missing

### ISSUE THREAD

**Issue by andyzll** [carla-simulator/map#53]
Hi,
I tried to use the ad_map_access module in qgiz 3.16.3 but I get an import error that the metadata file is missing.
I set the python-paths according to https://ad-map-access.readthedocs.io/en/latest/ad_map_access_qgis/ad_map_access_qgis/#how-to-use-the-tool
and included the  QGIS_PLUGINPATH in Qgizs (Settings-Options-System-Enviroment).

In the plug-in manager the module appears and is coloured in red "Extension is defect - Meta data is missing"

Is there an issue in the implementation or did I just miss something?

![grafik](https://user-images.githubusercontent.com/83449055/117028442-02963080-acfe-11eb-8b4b-b624760b3c97.png)

Thanks a lot!

**Comment by berndgassmann** [comment]
Hmm, 
did you try to just take the pre-built package from here:
https://github.com/carla-simulator/map/releases/tag/v2.4.3

I used those with 3.16 and now on ubunutu 20.04 even with 3.18.

When I look into your error above, one possible issue could be for sure that the pluginpath isn't set correctly, it's listing icons.... strange. 
When I look into the docu here (QGIS_PLUGINPATH=install/ad_map_access_qgis/share/qgis/python/plugins/ad_map_access_qgis) I believe the path is too long indeed and qgis is looking at the subfolder "icons" and has an error.
The correct path should be without the extension:
QGIS_PLUGINPATH=install/ad_map_access_qgis/share/qgis/python/plugins

Can you try this, please?

**Comment by berndgassmann** [comment]
I've created a PR to fix the docu here.
By the way: In the BUILDING section is was mentioned correctly
https://ad-map-access.readthedocs.io/en/latest/BUILDING/
```
  map$> export QGIS_PLUGINPATH=<path/to/>map/install/ad_map_access_qgis/share/qgis/python/plugins
```

**Comment by andyzll** [comment]
Hi Bernd,
adapting the paths helped qgis to find the package, but displayed me an compatibility issue. Probably my version was outdated.
(This Extension is not compatible with this qgis version - Extension for QGIS 2.0-2.99)

Downloading the pre-built package for ubuntu-18.04 solved my problem.
Thanks a lot
