### ISSUE TITLE
Windows Support 

### ISSUE THREAD

**Issue by kmeids** [carla-simulator/map#58]
Hello,
Is there windows support for this package?
Thanks!

**Comment by berndgassmann** [comment]
I don't know how far away it is from windows compilation. We never tried and don't plan to do so.
Colcon, cmake, should be available there, too. The code itself should also not contain much linux specifics; but I can't tell what it would take to get it compiled there.

**Comment by yaoshu666** [comment]
When I run qgis and install the plugin from the plugins menu (Plugins > Manage and Install Plugins > Install from ZIP), choose the zip file that was previously downloaded,it shows ''No module named 'ad_map_access' ''.however, ad-map-access python only for linux. Is there windows support for this package?
