### ISSUE TITLE
'No module named 'ad_map_access' ''

### ISSUE THREAD

**Issue by yaoshu666** [carla-simulator/map#67]
When I run qgis and install the plugin from the plugins menu (Plugins > Manage and Install Plugins > Install from ZIP), choose the zip file that was previously downloaded,it shows ''No module named 'ad_map_access' ''.however, ad-map-access python only for linux. Is there windows support for this package?

**Comment by berndgassmann** [comment]
Hi,

currently there is no windows support available yet. See also issue #58. 
But the team is currently discussing the possibilities and effort on this.

**Comment by jin-111** [comment]
How to get ad-map-access python? I cannot download by pip with
`pip install ad-map-access`

**Comment by berndgassmann** [comment]
Hmm, strange.
If you look at the files section at [PyPi](https://pypi.org/project/ad-map-access/#files) you see that ad-map-access is currently published for python 2.7, 3.6, 3.7 and 3.8. And especiallly it is build even on a Ubunutu [docker](https://github.com/carla-simulator/map/blob/master/.github/workflows/wheels/docker/Dockerfile)

So what python version is your current configured standard?
You might want to try it with python3. 

Or it's maybe some proxy issue, but then other PyPi packages should also not work..

**Comment by jin-111** [comment]
> Hmm, strange.
> If you look at the files section at [PyPi](https://pypi.org/project/ad-map-access/#files) you see that ad-map-access is currently published for python 2.7, 3.6, 3.7 and 3.8. And especiallly it is build even on a Ubunutu [docker](https://github.com/carla-simulator/map/blob/master/.github/workflows/wheels/docker/Dockerfile)
> 
> So what python version is your current configured standard?
> You might want to try it with python3.
> 
> Or it's maybe some proxy issue, but then other PyPi packages should also not work..

Thank you!Your suggestion reminded me. I checked the version of PIP and found that the version of PIP is 9. 0. 1. I update PIP to the latest version. It works.
