### ISSUE TITLE
Missing python3 PyPi package

### ISSUE THREAD

**Issue by ralwing** [carla-simulator/map#78]
Hi,
According to [this message](https://github.com/carla-simulator/map/issues/67#issuecomment-922433973) this package should be available for Python3 on PyPi repo. However neither pip nor the [PyPi search](https://pypi.org/search/?q=ad-map-access&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3) finds it.
The [package page](https://pypi.org/project/ad-map-access/) also (in Programming Language section) also reports only Python2. 
Thanks!

**Comment by ralwing** [comment]
Ok, upgrade to the newest pip solved the problem. Thank You:
```
#pip install ad-map-access
Collecting ad-map-access
  Downloading ad_map_access-2.6.0-cp38-cp38-manylinux_2_27_x86_64.whl (11.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 30.1 MB/s eta 0:00:00
Collecting ad-physics>=2.6.0
  Downloading ad_physics-2.6.0-cp38-cp38-manylinux_2_27_x86_64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 48.2 MB/s eta 0:00:00
Installing collected packages: ad-physics, ad-map-access
Successfully installed ad-map-access-2.6.0 ad-physics-2.6.0

#pip --version
pip 22.0.4 from /usr/local/lib/python3.8/dist-packages/pip (python 3.8)
```

**Comment by Xiaowuzjj** [comment]
![image](https://github.com/user-attachments/assets/51fdd8c1-fa64-434d-9cd2-aeae9700ac6d)
Why can’t I download pip after I upgraded it?
